### ISSUE TITLE
Mobile-specific location override

### ISSUE THREAD

**Issue by jbranigan** [mapbox/storytelling#10]
Provide a config option for a mobile screen location for each chapter. This accommodates some custom location setups that may shift the center of focus a bit to the left or right when the chapter alignment is to the side, and also a smaller zoom level to ensure features are visible on smaller screens.

Completed sections:
- [ ] Vanilla JS
- [ ] React JS
- [ ] README
- [ ] Vanilla examples
- [ ] React examples

**Comment by chriswhong** [comment]
closing stale issues
