### ISSUE TITLE
Add class for a hidden chapter

### ISSUE THREAD

**Issue by jbranigan** [mapbox/storytelling#13]
A hidden chapter would be invisible to the reader, but would trigger a map transition when it is scrolled to. Can use a new CSS class to hide it, and a corresponding config property.

Completed sections:
- [ ] Vanilla JS
- [ ] React JS
- [ ] README
- [ ] Vanilla examples
- [ ] React examples

**Comment by cormundo** [comment]
Was this completed?

**Comment by jbranigan** [comment]
Hi @cormundo, still working on a set of tasks for an update, but here's how to do it in the mean time. Find the chapter `id` for the chapter you want to hide, and then add some CSS in the <style> section of `index.html` before the media query:
```
        #id-of-the-block-you-want-to-hide {
            visibility: hidden;
        }
```

**Comment by jbranigan** [comment]
Added
