### ISSUE TITLE
Third party vector tile source in story telling

### ISSUE THREAD

**Issue by maxwell-oroark** [mapbox/storytelling#21]
Does this support adding vector tile layers that are **_not_** hosted in mapbox studio?

*edit* looks like the react version does expose `transformRequest` function :D so I could pass credentials... only thing I'm not sure on is would I be okay to pass my own paint style layer for that custom tile source using the template or would I have to build that logic into the `App.js` file

**Comment by jbranigan** [comment]
Hi @maxwell-oroark. The layer toggle is designed to work with a Studio style (and uses the layer name to access a specific layer). If you want to add a tileset that is outside a Studio map, you could add it in the script in the `App.js` file as you would with any GL JS map (https://docs.mapbox.com/mapbox-gl-js/example/third-party/). It won't turn on/off via the config settings, but it will be there for context.
