### ISSUE TITLE
Support masked/scrub transitions

### ISSUE THREAD

**Issue by yuletide** [mapbox/storytelling#22]
For some reason [this story](https://www.washingtonpost.com/graphics/2020/world/amp-stories/mapping-coronavirus/) shows up with amazing scrub and mask transitions when [rendered by Apple News ](https://apple.news/AWO4q8kxHS3q_hLMWIcglBw).

Could be implemented with https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-compare/ (has an option for `vertical`)?

![Screen Recording 2020-01-29 at 10 39 AM](https://user-images.githubusercontent.com/58695/73386529-d894c980-4283-11ea-99b4-87d5325f0a6c.gif)

**Comment by chriswhong** [comment]
closing stale
