### ISSUE TITLE
iOS scrolling breaks on map rendering using Vanilla

### ISSUE THREAD

**Issue by cameronkruse** [mapbox/storytelling#29]
I'm using the vanilla plugin and I've been running into a problem where scrolling stops working on ios when the map has to render after loading. I dug into it a little bit and found that the features layers seem to disappear when the map has to render in the browser. 

Here is a screenshot of the layers visible when it's frozen and the features layers have disappeared: 
![Screen Shot 2020-05-16 at 1 44 12 PM](https://user-images.githubusercontent.com/14115927/82129984-0db62080-977c-11ea-888a-ae8df5a12b77.png)

Here is a screenshot of the layers when things are working properly:
![Screen Shot 2020-05-16 at 1 53 20 PM](https://user-images.githubusercontent.com/14115927/82130038-a2b91980-977c-11ea-9212-0c7a3ccc8735.png)

If I rotate the device it starts working again and I can scroll normally. 

You can find a live version of the project here: http://cameronwkruse.com/home/projects/runthestairs/

Originally, I assumed this may be connected to the GEOJSON map layers I was adding, but it seems like you can replicate whenever the map has to load a new rendering.

**Comment by lobenichou** [comment]
I've been working on this all evening and the issue is actually due to `touch-action` being set to `none` on the canvas container. This bug has been around for a while. @jbranigan, fyi, I fixed it by adding 

```
.mapboxgl-canvas-container.mapboxgl-touch-zoom-rotate.mapboxgl-touch-drag-pan, .mapboxgl-canvas-container.mapboxgl-touch-zoom-rotate.mapboxgl-touch-drag-pan .mapboxgl-canvas {touch-action: unset;}
```

to the css. Since the map is always in `position:fixed` and in the background, you shouldn't need it at all. Happy to make a PR.

**Comment by jbranigan** [comment]
@lobenichou — ahh, amazing! This fixed a broken project of mine that I hadn't been able to figure out. If you want to make a PR for the contribution, I'll merge it right away. Happy to take care of it if you don't have time.

**Comment by lobenichou** [comment]
hmm seems like i don't have permissions to make a PR?

**Comment by cameronkruse** [comment]
@lobenichou 's fix worked for me. Thanks for the trouble shooting! I'm going to close the issue, but feel free to reopen if there is a different flow the team uses.
