### ISSUE TITLE
Any plans for adding a Create Story Form workflow?

### ISSUE THREAD

**Issue by nonoumasy** [mapbox/storytelling#30]
I was thinking of extending this solution to an even wider audience by creating a website where the user can create the stories and chapters using a form. The user first clicks on 'New Story' and proceeds to add data for each subsequent chapter and then pressing 'done'. The map is generated and the data saved in a mongo database so yes I guess there will be authentication, login and the basic CRUD functionality. 
Do you have some high-level tips?

![form](https://user-images.githubusercontent.com/6312676/87960471-2fc46b80-ca69-11ea-967c-1bd831116513.png)

**Comment by stevebutton** [comment]
I find this possibility interesting - not so much for creating the entire story, but to allow for user input of content into an existing map.

**Comment by jbranigan** [comment]
We don't have plans at this time to build a UI that generates a config file, but have spoken with some companies interested in building something into their CMS. Aside from the text content, the other main inputs are the chapter location, and handling layers when the chapter is active. 

For the location aspect, you might consider incuding something like the helper.html file alongside this form, so the users can zoom and tilt the map and choose their location. 

Layer handling might be a bit more involved, but you can access the list of available layers in a style with `map.getStyle()` https://docs.mapbox.com/mapbox-gl-js/api/map/#map#getstyle

**Comment by nonoumasy** [comment]
Thanks @jbranigan

**Comment by nonoumasy** [comment]
https://stories-nine.vercel.app/ - just wanted to circle back. I finally made a scrollyTelling site where Users can add their stories using a form.

<img width="1440" alt="Screen Shot 2021-11-08 at 4 04 05 AM" src="https://user-images.githubusercontent.com/6312676/140738897-d6251a81-e95f-4336-ab6c-24051bab581d.png">
m.

**Comment by stevebutton** [comment]
very interesting nono - I'm doing something very similar, will send you a link.
