### ISSUE TITLE
links in AttributionControl on map should be clickable

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/storytelling#34]
At least in the demo at https://demos.mapbox.com/scrollytelling/ (not sure if it applies to all pages created with this) the Mapbox logo (bottom left) and attribution links (bottom right) are not clickable due to the `story` div.

To fix this I think the `story` div should sit between the `mapboxgl-canvas-container` and `mapboxgl-control-container` elements inside the map.

**Comment by jbranigan** [comment]
Fixed
