### ISSUE TITLE
Does anyone know how to add a video? 

### ISSUE THREAD

**Issue by danielasenars** [mapbox/storytelling#37]

**Comment by gisdirk** [comment]
Same question here. Does anybody know how to include a video (or even audio)?

**Comment by jbranigan** [comment]
The `description` field in the configuration file gets rendered as HTML, not just text. You can include a video embed HTML snippet in that field to display the video in one of the chapter blocks. Escape single quotes with a backslash like `\'`, if needed. Hope this helps!

**Comment by gisdirk** [comment]
It works, thanks very much !

Not sure what you mean by "_Escape single quotes with a backslash like \', if needed_" ?

**Comment by geografa** [comment]
Escaping quotes may be needed for some video URLs. ref: https://stackoverflow.com/questions/18886596/replace-all-quotes-in-a-string-with-escaped-quotes. This [example](https://supmap.org/spots/) has some video links.
