### ISSUE TITLE
Custom layers in config.js 

### ISSUE THREAD

**Issue by Sangarshanan** [mapbox/storytelling#4]
Hey, I just wanted to know if it was possible to add custom layers such as https://docs.mapbox.com/mapbox-gl-js/examples/#layers instead using layers from mapbox studio

**Comment by jbranigan** [comment]
Hi @Sangarshanan, the `config.js` layers are limited to Studio layers at this point. It's certainly possible to add in custom layers in the `index.html` file, though they will always display and aren't available for toggling the way Studio layers are. Check out this post for some more info on adding custom layers in GL JS: https://blog.mapbox.com/launching-custom-layers-with-uber-2a235841a125

**Comment by Sangarshanan** [comment]
Got it, Thanks  :+1:
