### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by mr-fuller** [mapbox/storytelling#40]
I've been using the vanilla template with enough chapters that I thought some kind of navigation bar functionality might be useful to jump to the larger sections in which I had been grouping chapters (https://tmacog-gov-members.netlify.app/).

The quick-and-dirty solution I came up with was to create a first chapter that had links to each section-heading chapter in the description, then each section-heading chapter has a link back to the top at the end of its description.

I tried putting the links in the byline of the header, as I thought that would have looked better, but I don't think it worked. Should I be able to put any HTML in any parts of the header?

**Comment by jbranigan** [comment]
Hi @mr-fuller , if you'd like to add HTML into the byline, you can change the way the value is set. I use the `innerText` when HTML isn't required, but you could change where the byline is set to use `innerHTML` instead. This is where to change it in your `index.html`:
```
if (config.byline) {
    var bylineText = document.createElement('p');
    bylineText.innerText = config.byline; // Change this to innerHTML
    header.appendChild(bylineText);
}
```

**Comment by mr-fuller** [comment]
Got it working. Thanks so much!
