### ISSUE TITLE
Add legend and filters

### ISSUE THREAD

**Issue by angelinaRC** [mapbox/storytelling#46]
Hey everyone,

The template is so helpful. Many thanks to the Mapbox team for putting it together. 

Does anyone know how one could add a legend and potentially also filters to the map? They will of course be different for every chapter as different layers will be shown. 
I saw it being implemented here https://comet.dlsu.edu.ph/riesgo-vis/ but they are using React as well and I would like to stick to my index + config file.

Thanks in advance

**Comment by rudokemper** [comment]
I adapted a way to do this using HTML/CSS and JS for this story map: http://lab.digital-democracy.org/mapa-sinangoe/

If you take a look at the code, it involves adding some divs with your map legend content, some styling including setting these to be hidden by default, and then some show/hide code added to `scroller.onStepEnter`.
