### ISSUE TITLE
[Feature Request] Trace and follow a route

### ISSUE THREAD

**Issue by cedricdelpoux** [mapbox/storytelling#6]
Mapbox storytelling seems interesting but for me there is a missing important feature: The ability to following a route like [this example](https://tympanus.net/Development/StorytellingMap/).

It would be awesome if something relative could be implemented.

**Comment by jbranigan** [comment]
@cedricdelpoux check out this great work by @willymaps:
http://www.formerspatial.com/scrolly-drive

**Comment by cedricdelpoux** [comment]
@jbranigan Thank you for sharing this extension. It is a nice feature !

**Comment by cedricdelpoux** [comment]
I finally implement my own but it's not perfect https://cedricdelpoux.fr/voyage/islande/mon-voyage-autour-de-l-islande

**Comment by jbranigan** [comment]
_Really_ nice work on that map, looks like an amazing trip, too!

**Comment by stevebutton** [comment]
very nice Cedric - Im doing something similar with automatic kml that Google generates in My Maps history. Nice graphic aesthetic as well.

**Comment by cedricdelpoux** [comment]
I use data from Google MyMaps too. I created a [Gatsby Source Google MyMaps](https://github.com/cedricdelpoux/gatsby-source-google-mymaps) plugin in case you use Gatsby
