### ISSUE TITLE
adding markers for specific chapter of the story telling map 

### ISSUE THREAD

**Issue by MM-cyi** [mapbox/storytelling#60]
Hi there. 

First off, let me congratulate of the AMAZING work you did. It is very impressive and looks very elegant. 

I wonder if there is any chance to add markers when scrolling along the story, like for instance: 
I move to chapter 2, and suddenly (fading in) I see some markers appearing. 
The when scrolling on, these markers disappear and leave room to others. 

I tried having a look at the config map, and have seen a sequence of json-like instances. However, cant figure out how and where to add the above feature. 

Thank you and keep up the amazing work.

**Comment by chriswhong** [comment]
You could use the `callback` option for a chapter, and then add javascript code to show and hide markers. https://docs.mapbox.com/mapbox-gl-js/example/add-a-marker/
