### ISSUE TITLE
Example map style not available in bike-philly

### ISSUE THREAD

**Issue by SiggyF** [mapbox/storytelling#65]
The example uses the following style.

```
mapbox://styles/branigan/cjzsvonse027m1co4nkxp13b3
```
This style is referenced in the [bike-philly](https://github.com/mapbox/storytelling/blob/607ad6310990cb698f62614c8e5d59dc02ab8a79/example/bike-philly/config.js#L2) example.  

Unfortunately, this style is not available (also not to my paid account). It gives the following error:

```
Internal error
Account over limit.
```

Would it be possible to re-enable that style or use another shared style?

**Comment by chriswhong** [comment]
Thanks for flagging, the examples in this repo will be removed and we will instead reference this demo: https://labs.mapbox.com/storytelling/ (which is source available)
