### ISSUE TITLE
[Feature Request] Highlight specific country

### ISSUE THREAD

**Issue by cedricdelpoux** [mapbox/storytelling#8]
Most of the time, when I need to use storytelling, I want to restrict the story to a specific region.

In Mapbox it is possible to [style a single country](https://docs.mapbox.com/help/tutorials/style-single-country/) but it could be awesome to do this directly from the storytelling config.

What do you think?

**Comment by jbranigan** [comment]
Hi @cedricdelpoux , by using the approach in that link, you can use Studio to style a country on it's own layer (and as many other countries as you want on their own layers). Then in the config, turn on and off the country layer that is relevant to that section in your story. 

Adding features to this template is a balance of increasing functionality while keeping the complexity relatively low. We want to keep it accessible to people without much coding experience. This has the added benefit of making it easier for experienced developers to extend and customize the template. Hope this helps!

**Comment by cedricdelpoux** [comment]
I found [this tutorial](https://docs.mapbox.com/help/tutorials/style-single-country/) that helped a lot. Thank you
