### ISSUE TITLE
Provide map transitions options

### ISSUE THREAD

**Issue by jbranigan** [mapbox/storytelling#9]
In the config, provide a way to choose between `flyTo` and `jumpTo`. 

- some animations take a long time to finish and vector tiles drop, resulting in poor ux
    - if the start and end zooms are tight, and the distance is far
    - if the map uses a heavy tileset like terrain
    - if the author expects a slow user connection

Completed sections:
- [x] Vanilla JS
- [ ] React JS
- [x] README
- [ ] Vanilla examples
- [ ] React examples

**Comment by jbranigan** [comment]
Question: should this be global or per chapter?

**Comment by jbixon13** [comment]
I would have a use case that benefits from this option being per-chapter. Using a similar scale of the example of Glacier National Park.
- I would use jumpTo to transition from Missoula airport to East end of the park to avoid tiles dropping
- I would use flyTo when transitioning between subsequent hike locations as they're much closer

**Comment by jbranigan** [comment]
Added
